title: Set a sprite's coordinates in Scratch
hero_image: images/banner.png
description: How to set a sprite's coordinates in Scratch
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - title: Set coordinates
