---
title: Set a sprite's coordinates
hero_image: images/banner.png
description: How to set a sprite's coordinates in Scratch
original_url:
theme: nguyên mẫu cc
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Set coordinates
