---
title: Set a sprite's coordinates
hero_image: images / banner.png
description: Scratch'te kuklanın konumu nasıl belirlenir
original_url:
theme: cc-prototip
duration: 1
listed: false
ingredient: true
copyedit: true
interests:
technologies: "scratch"
steps:
  - 
    title: Konumu belirle
